// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc_error_codes.proto

package mtproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TLRpcErrorCodes int32

const (
	// 	Error handling
	//
	// 	There will be errors when working with the API, and they must be correctly handled on the client.
	//
	// 	An error is characterized by several parameters:
	//
	// 	Error Code
	// 	Similar to HTTP status. Contains information on the type of error that occurred: for example,
	// 	a data input error, privacy error, or server error. This is a required parameter.
	//
	// 	Error Type
	// 	A string literal in the form of /[A-Z_0-9]+/, which summarizes the problem. For example, AUTH_KEY_UNREGISTERED.
	// 	This is an optional parameter.
	//
	// 	Error Description
	// 	May contain more detailed information on the error and how to resolve it,
	// 	for example: authorization required, use auth.* methods. Please note that the description text is subject to change,
	// 	one should avoid tying application logic to these messages. This is an optional parameter.
	//
	// 	Error Constructors
	// 	There should be a way to handle errors that are returned in rpc_error constructors.
	//
	// 	If an error constructor does not differentiate between type and description
	// 	but instead contains a single field called error_message (as in the example above),
	// 	it must be split into 2 components, for example, using the following regular expression: /^([A-Z_0-9]+)(: (.+))?/.
	//
	// Protobuf3 enum first is 0
	TLRpcErrorCodes_ERROR_CODE_OK TLRpcErrorCodes = 0
	// 303 ERROR_SEE_OTHER
	//
	// The request must be repeated, but directed to a different data center.
	//
	// FILE_MIGRATE_X: the file to be accessed is currently stored in a different data center.
	// PHONE_MIGRATE_X: the phone number a user is trying to use for authorization is associated with a different data center.
	// NETWORK_MIGRATE_X: the source IP address is associated with a different data center (for registration)
	// USER_MIGRATE_X: the user whose identity is being used to execute
	// 				   queries is associated with a different data center (for registration)
	//
	// In all these cases, the error description’s string literal
	// 		contains the number of the data center (instead of the X) to which the repeated query must be sent.
	// More information about redirects between data centers »
	//
	TLRpcErrorCodes_FILE_MIGRATE_X    TLRpcErrorCodes = 303000
	TLRpcErrorCodes_PHONE_MIGRATE_X   TLRpcErrorCodes = 303001
	TLRpcErrorCodes_NETWORK_MIGRATE_X TLRpcErrorCodes = 303002
	TLRpcErrorCodes_USER_MIGRATE_X    TLRpcErrorCodes = 303003
	TLRpcErrorCodes_ERROR_SEE_OTHER   TLRpcErrorCodes = 303
	// 400 BAD_REQUEST
	//
	// The query contains errors. In the event that a request was created using a form
	// and contains user generated data,
	// the user should be notified that the data must be corrected before the query is repeated.
	//
	//
	// Examples of Errors:
	// 	FIRSTNAME_INVALID: The first name is invalid
	// 	LASTNAME_INVALID: The last name is invalid
	// 	PHONE_NUMBER_INVALID: The phone number is invalid
	// 	PHONE_CODE_HASH_EMPTY: phone_code_hash is missing
	// 	PHONE_CODE_EMPTY: phone_code is missing
	// 	PHONE_CODE_EXPIRED: The confirmation code has expired
	// 	API_ID_INVALID: The api_id/api_hash combination is invalid
	// 	PHONE_NUMBER_OCCUPIED: The phone number is already in use
	// 	PHONE_NUMBER_UNOCCUPIED: The phone number is not yet being used
	// 	USERS_TOO_FEW: Not enough users (to create a chat, for example)
	// 	USERS_TOO_MUCH: The maximum number of users has been exceeded (to create a chat, for example)
	// 	TYPE_CONSTRUCTOR_INVALID: The type constructor is invalid
	// 	FILE_PART_INVALID: The file part number is invalid
	// 	FILE_PARTS_INVALID: The number of file parts is invalid
	// 	FILE_PART_Х_MISSING: Part X (where X is a number) of the file is missing from storage
	// 	MD5_CHECKSUM_INVALID: The MD5 checksums do not match
	// 	PHOTO_INVALID_DIMENSIONS: The photo dimensions are invalid
	// 	FIELD_NAME_INVALID: The field with the name FIELD_NAME is invalid
	// 	FIELD_NAME_EMPTY: The field with the name FIELD_NAME is missing
	// 	MSG_WAIT_FAILED: A waiting call returned an error
	//
	TLRpcErrorCodes_FIRSTNAME_INVALID        TLRpcErrorCodes = 400000
	TLRpcErrorCodes_LASTNAME_INVALID         TLRpcErrorCodes = 400001
	TLRpcErrorCodes_PHONE_NUMBER_INVALID     TLRpcErrorCodes = 400002
	TLRpcErrorCodes_PHONE_CODE_HASH_EMPTY    TLRpcErrorCodes = 400003
	TLRpcErrorCodes_PHONE_CODE_EMPTY         TLRpcErrorCodes = 400004
	TLRpcErrorCodes_PHONE_CODE_EXPIRED       TLRpcErrorCodes = 400005
	TLRpcErrorCodes_API_ID_INVALID           TLRpcErrorCodes = 400006
	TLRpcErrorCodes_PHONE_NUMBER_OCCUPIED    TLRpcErrorCodes = 400007
	TLRpcErrorCodes_PHONE_NUMBER_UNOCCUPIED  TLRpcErrorCodes = 400008
	TLRpcErrorCodes_USERS_TOO_FEW            TLRpcErrorCodes = 400009
	TLRpcErrorCodes_USERS_TOO_MUCH           TLRpcErrorCodes = 400010
	TLRpcErrorCodes_TYPE_CONSTRUCTOR_INVALID TLRpcErrorCodes = 400011
	TLRpcErrorCodes_FILE_PART_INVALID        TLRpcErrorCodes = 400012
	TLRpcErrorCodes_FILE_PART_X_MISSING      TLRpcErrorCodes = 400013
	TLRpcErrorCodes_MD5_CHECKSUM_INVALID     TLRpcErrorCodes = 400014
	TLRpcErrorCodes_PHOTO_INVALID_DIMENSIONS TLRpcErrorCodes = 400015
	TLRpcErrorCodes_FIELD_NAME_INVALID       TLRpcErrorCodes = 400016
	TLRpcErrorCodes_FIELD_NAME_EMPTY         TLRpcErrorCodes = 400017
	TLRpcErrorCodes_MSG_WAIT_FAILED          TLRpcErrorCodes = 400018
	// PHONE_NUMBER_BANNED = 4000;
	// android client code:
	//    if (error.code == 400 && "PARTICIPANT_VERSION_OUTDATED".equals(error.text)) {
	//        callFailed(VoIPController.ERROR_PEER_OUTDATED);
	TLRpcErrorCodes_PARTICIPANT_VERSION_OUTDATED TLRpcErrorCodes = 400019
	TLRpcErrorCodes_USER_RESTRICTED              TLRpcErrorCodes = 400020
	TLRpcErrorCodes_NAME_NOT_MODIFIED            TLRpcErrorCodes = 400021
	TLRpcErrorCodes_USER_NOT_MUTUAL_CONTACT      TLRpcErrorCodes = 400022
	TLRpcErrorCodes_BOT_GROUPS_BLOCKED           TLRpcErrorCodes = 400023
	TLRpcErrorCodes_GUEST_USER_NOT_EXISTS        TLRpcErrorCodes = 400024
	// user
	TLRpcErrorCodes_USER_NOT_EXISTS TLRpcErrorCodes = 400400
	// team error
	TLRpcErrorCodes_TEAM_NOT_EXISTS                                          TLRpcErrorCodes = 400401
	TLRpcErrorCodes_TEAM_EXPEL_USER_CAN_NOT_EXPEL_YOURSELF_CODE              TLRpcErrorCodes = 400410
	TLRpcErrorCodes_TEAM_EXPEL_USER_USER_NOT_IN_TEAM_CODE                    TLRpcErrorCodes = 400411
	TLRpcErrorCodes_TEAM_EXPEL_USER_ADMIN_CAN_NOT_EXPEL_ADMIN_AND_OWNER_CODE TLRpcErrorCodes = 400412
	TLRpcErrorCodes_TEAM_EXPEL_USER_NOT_ADMIN_CODE                           TLRpcErrorCodes = 400413
	TLRpcErrorCodes_TEAM_INVITE_JOIN_INVITEES_NOT_EXISTS_CODE                TLRpcErrorCodes = 400420
	TLRpcErrorCodes_TEAM_INVITE_JOIN_ALREADY_IN_TEAM_CODE                    TLRpcErrorCodes = 400421
	TLRpcErrorCodes_TEAM_JOIN_ALREADY_IN_TEAM_CODE                           TLRpcErrorCodes = 400430
	TLRpcErrorCodes_TEAM_QUIT_NOT_IN_TEAM_CODE                               TLRpcErrorCodes = 400440
	TLRpcErrorCodes_TEAM_UPDATE_NOT_PERMISSION_CODE                          TLRpcErrorCodes = 400450
	TLRpcErrorCodes_TEAM_UPDATE_HANDOVER_PERSON_NOT_IN_TEAM_CODE             TLRpcErrorCodes = 400451
	TLRpcErrorCodes_FILE_REFERENCE_X                                         TLRpcErrorCodes = 400500
	TLRpcErrorCodes_FILE_TOKEN_INVALID                                       TLRpcErrorCodes = 400501
	TLRpcErrorCodes_REQUEST_TOKEN_INVALID                                    TLRpcErrorCodes = 400502
	//
	TLRpcErrorCodes_PHONE_CODE_INVALID      TLRpcErrorCodes = 400025
	TLRpcErrorCodes_PHONE_NUMBER_BANNED     TLRpcErrorCodes = 400030
	TLRpcErrorCodes_SESSION_PASSWORD_NEEDED TLRpcErrorCodes = 400040
	// password
	TLRpcErrorCodes_CODE_INVALID          TLRpcErrorCodes = 400050
	TLRpcErrorCodes_PASSWORD_HASH_INVALID TLRpcErrorCodes = 400051
	TLRpcErrorCodes_NEW_PASSWORD_BAD      TLRpcErrorCodes = 400052
	TLRpcErrorCodes_NEW_SALT_INVALID      TLRpcErrorCodes = 400053
	TLRpcErrorCodes_EMAIL_INVALID         TLRpcErrorCodes = 400054
	TLRpcErrorCodes_EMAIL_UNCONFIRMED     TLRpcErrorCodes = 400055
	// username
	TLRpcErrorCodes_USERNAME_INVALID      TLRpcErrorCodes = 400060
	TLRpcErrorCodes_USERNAME_OCCUPIED     TLRpcErrorCodes = 400061
	TLRpcErrorCodes_USERNAMES_UNAVAILABLE TLRpcErrorCodes = 400062
	TLRpcErrorCodes_USERNAME_NOT_MODIFIED TLRpcErrorCodes = 400063
	TLRpcErrorCodes_USERNAME_NOT_OCCUPIED TLRpcErrorCodes = 400064
	// chat
	TLRpcErrorCodes_CHAT_ID_INVALID         TLRpcErrorCodes = 400070
	TLRpcErrorCodes_CHAT_NOT_MODIFIED       TLRpcErrorCodes = 400071
	TLRpcErrorCodes_PARTICIPANT_NOT_EXISTS  TLRpcErrorCodes = 400072
	TLRpcErrorCodes_NO_EDIT_CHAT_PERMISSION TLRpcErrorCodes = 400073
	TLRpcErrorCodes_CHAT_TITLE_NOT_MODIFIED TLRpcErrorCodes = 400074
	TLRpcErrorCodes_NO_CHAT_TITLE           TLRpcErrorCodes = 400075
	TLRpcErrorCodes_CHAT_ABOUT_NOT_MODIFIED TLRpcErrorCodes = 400076
	TLRpcErrorCodes_CHAT_ADMIN_REQUIRED     TLRpcErrorCodes = 400077
	TLRpcErrorCodes_PARTICIPANT_EXISTED     TLRpcErrorCodes = 400078
	// channel
	TLRpcErrorCodes_CHANNEL_PRIVATE                TLRpcErrorCodes = 400080
	TLRpcErrorCodes_CHANNEL_PUBLIC_GROUP_NA        TLRpcErrorCodes = 400081
	TLRpcErrorCodes_USER_BANNED_IN_CHANNEL         TLRpcErrorCodes = 400082
	TLRpcErrorCodes_CHANNELS_ADMIN_PUBLIC_TOO_MUCH TLRpcErrorCodes = 40083
	TLRpcErrorCodes_CHANNELS_TOO_MUCH              TLRpcErrorCodes = 400084
	TLRpcErrorCodes_NO_INVITE_CHANNEL_PERMISSION   TLRpcErrorCodes = 400085
	// invite, user banned.
	TLRpcErrorCodes_INVITE_HASH_EXPIRED TLRpcErrorCodes = 400090
	TLRpcErrorCodes_INVITE_HASH_INVALID TLRpcErrorCodes = 400091
	// access
	TLRpcErrorCodes_ACCESS_HASH_INVALID  TLRpcErrorCodes = 400200
	TLRpcErrorCodes_INPUT_CHANNEL_EMPTY  TLRpcErrorCodes = 400201
	TLRpcErrorCodes_USER_NOT_PARTICIPANT TLRpcErrorCodes = 400202
	TLRpcErrorCodes_PEER_ID_INVALID      TLRpcErrorCodes = 400203
	TLRpcErrorCodes_CHANNEL_ID_INVALID   TLRpcErrorCodes = 400204
	// message
	TLRpcErrorCodes_MESSAGE_ID_INVALID        TLRpcErrorCodes = 400210
	TLRpcErrorCodes_MESSAGE_EDIT_TIME_EXPIRED TLRpcErrorCodes = 400211
	TLRpcErrorCodes_MESSAGE_NOT_MODIFIED      TLRpcErrorCodes = 400212
	TLRpcErrorCodes_MESSAGE_EMPTY             TLRpcErrorCodes = 400213
	TLRpcErrorCodes_USER_LEFT_CHAT            TLRpcErrorCodes = 400300
	TLRpcErrorCodes_USER_KICKED               TLRpcErrorCodes = 400301
	TLRpcErrorCodes_USER_ALREADY_PARTICIPANT  TLRpcErrorCodes = 400302
	TLRpcErrorCodes_BAD_REQUEST               TLRpcErrorCodes = 400
	// There was an unauthorized attempt to use functionality available only to authorized users.
	//
	// Examples of Errors:
	// 	AUTH_KEY_UNREGISTERED: The key is not registered in the system
	// 	AUTH_KEY_INVALID: The key is invalid
	// 	USER_DEACTIVATED: The user has been deleted/deactivated
	// 	SESSION_REVOKED: The authorization has been invalidated, because of the user terminating all sessions
	// 	SESSION_EXPIRED: The authorization has expired
	// 	ACTIVE_USER_REQUIRED: The method is only available to already activated users
	// 	AUTH_KEY_PERM_EMPTY: The method is unavailble for temporary authorization key, not bound to permanent
	//
	TLRpcErrorCodes_AUTH_KEY_UNREGISTERED TLRpcErrorCodes = 401000
	TLRpcErrorCodes_AUTH_KEY_INVALID      TLRpcErrorCodes = 401001
	TLRpcErrorCodes_USER_DEACTIVATED      TLRpcErrorCodes = 401002
	TLRpcErrorCodes_SESSION_REVOKED       TLRpcErrorCodes = 401003
	TLRpcErrorCodes_SESSION_EXPIRED       TLRpcErrorCodes = 401004
	TLRpcErrorCodes_ACTIVE_USER_REQUIRED  TLRpcErrorCodes = 401005
	TLRpcErrorCodes_AUTH_KEY_PERM_EMPTY   TLRpcErrorCodes = 401006
	// Only a small portion of the API methods are available to unauthorized users:
	//
	// auth.sendCode
	// auth.sendCall
	// auth.checkPhone
	// auth.signUp
	// auth.signIn
	// auth.importAuthorization
	// help.getConfig
	// help.getNearestDc
	//
	// Other methods will result in an error: 401 UNAUTHORIZED.
	TLRpcErrorCodes_UNAUTHORIZED TLRpcErrorCodes = 401
	// Privacy violation. For example, an attempt to write a message to someone who has blacklisted the current user.
	//
	//
	// android client code:
	//    } else if(error.code==403 && "USER_PRIVACY_RESTRICTED".equals(error.text)){
	//        callFailed(VoIPController.ERROR_PRIVACY);
	TLRpcErrorCodes_USER_PRIVACY_RESTRICTED     TLRpcErrorCodes = 403001
	TLRpcErrorCodes_CALL_PROTOCOL_LAYER_INVALID TLRpcErrorCodes = 403002
	TLRpcErrorCodes_FORBIDDEN                   TLRpcErrorCodes = 403
	// 406
	// android client code:
	// }else if(error.code==406){
	//     callFailed(VoIPController.ERROR_LOCALIZED);
	TLRpcErrorCodes_ERROR_LOCALIZED TLRpcErrorCodes = 406000
	TLRpcErrorCodes_LOCALIZED       TLRpcErrorCodes = 406
	// The maximum allowed number of attempts to invoke the given method with the given input parameters has been exceeded.
	// For example, in an attempt to request a large number of text messages (SMS) for the same phone number.
	//
	// Error Example:
	// FLOOD_WAIT_X: A wait of X seconds is required (where X is a number)
	//
	TLRpcErrorCodes_FLOOD_WAIT_X TLRpcErrorCodes = 420000
	// PEER_FLOOD
	// FLOOD_WAIT
	TLRpcErrorCodes_FLOOD TLRpcErrorCodes = 420
	// An internal server error occurred while a request was being processed;
	// for example, there was a disruption while accessing a database or file storage.
	//
	// If a client receives a 500 error, or you believe this error should not have occurred,
	// please collect as much information as possible about the query and error and send it to the developers.
	TLRpcErrorCodes_INTERNAL              TLRpcErrorCodes = 500
	TLRpcErrorCodes_INTERNAL_SERVER_ERROR TLRpcErrorCodes = 500000
	// If a server returns an error with a code other than the ones listed above,
	// it may be considered the same as a 500 error and treated as an internal server error.
	//
	TLRpcErrorCodes_OTHER TLRpcErrorCodes = 501
	//    // OFFSET_INVALID
	//    // RETRY_LIMIT
	//    // FILE_TOKEN_INVALID
	//    // REQUEST_TOKEN_INVALID
	//
	//    // CHANNEL_PRIVATE
	//    // CHANNEL_PUBLIC_GROUP_NA
	//    // USER_BANNED_IN_CHANNEL
	//
	//
	//    // MESSAGE_NOT_MODIFIED
	//
	//    // USERS_TOO_MUCH
	//
	//    // -1000
	//
	//    /////////////////////////////////////////////////////////////
	//     // android client code:
	//       } else if (request instanceof TLRPC.TL_auth_resendCode) {
	//        if (error.text.contains("PHONE_NUMBER_INVALID")) {
	//            showSimpleAlert(fragment, LocaleController.getString("InvalidPhoneNumber", R.string.InvalidPhoneNumber));
	//        } else if (error.text.contains("PHONE_CODE_EMPTY") || error.text.contains("PHONE_CODE_INVALID")) {
	//            showSimpleAlert(fragment, LocaleController.getString("InvalidCode", R.string.InvalidCode));
	//        } else if (error.text.contains("PHONE_CODE_EXPIRED")) {
	//            showSimpleAlert(fragment, LocaleController.getString("CodeExpired", R.string.CodeExpired));
	//        } else if (error.text.startsWith("FLOOD_WAIT")) {
	//            showSimpleAlert(fragment, LocaleController.getString("FloodWait", R.string.FloodWait));
	//        } else if (error.code != -1000) {
	//            showSimpleAlert(fragment, LocaleController.getString("ErrorOccurred", R.string.ErrorOccurred) + "\n" + error.text);
	//        }
	//
	//     /////////////////////////////////////////////////////////////
	//        } else if (request instanceof TLRPC.TL_updateUserName) {
	//            switch (error.text) {
	//                case "USERNAME_INVALID":
	//                    showSimpleAlert(fragment, LocaleController.getString("UsernameInvalid", R.string.UsernameInvalid));
	//                    break;
	//                case "USERNAME_OCCUPIED":
	//                    showSimpleAlert(fragment, LocaleController.getString("UsernameInUse", R.string.UsernameInUse));
	//                    break;
	//                case "USERNAMES_UNAVAILABLE":
	//                    showSimpleAlert(fragment, LocaleController.getString("FeatureUnavailable", R.string.FeatureUnavailable));
	//                    break;
	//                default:
	//                    showSimpleAlert(fragment, LocaleController.getString("ErrorOccurred", R.string.ErrorOccurred));
	//                    break;
	//            }
	//
	//     /////////////////////////////////////////////////////////////
	//            } else if (request instanceof TLRPC.TL_payments_sendPaymentForm) {
	//            switch (error.text) {
	//                case "BOT_PRECHECKOUT_FAILED":
	//                    showSimpleToast(fragment, LocaleController.getString("PaymentPrecheckoutFailed", R.string.PaymentPrecheckoutFailed));
	//                    break;
	//                case "PAYMENT_FAILED":
	//                    showSimpleToast(fragment, LocaleController.getString("PaymentFailed", R.string.PaymentFailed));
	//                    break;
	//                default:
	//                    showSimpleToast(fragment, error.text);
	//                    break;
	//            }
	//        } else if (request instanceof TLRPC.TL_payments_validateRequestedInfo) {
	//            switch (error.text) {
	//                case "SHIPPING_NOT_AVAILABLE":
	//                    showSimpleToast(fragment, LocaleController.getString("PaymentNoShippingMethod", R.string.PaymentNoShippingMethod));
	//                    break;
	//                default:
	//                    showSimpleToast(fragment, error.text);
	//                    break;
	//            }
	//        }
	//
	//     /////////////////////////////////////////////////////////////
	//
	//        } else {
	//            if (error.text.equals("2FA_RECENT_CONFIRM")) {
	//                needShowAlert(LocaleController.getString("AppName", R.string.AppName), LocaleController.getString("ResetAccountCancelledAlert", R.string.ResetAccountCancelledAlert));
	//            } else if (error.text.startsWith("2FA_CONFIRM_WAIT_")) {
	//                Bundle params = new Bundle();
	//                params.putString("phoneFormated", requestPhone);
	//                params.putString("phoneHash", phoneHash);
	//                params.putString("code", phoneCode);
	//                params.putInt("startTime", ConnectionsManager.getInstance().getCurrentTime());
	//                params.putInt("waitTime", Utilities.parseInt(error.text.replace("2FA_CONFIRM_WAIT_", "")));
	//                setPage(8, true, params, false);
	//            } else {
	TLRpcErrorCodes_OTHER2 TLRpcErrorCodes = 502
	// db error
	TLRpcErrorCodes_DBERR      TLRpcErrorCodes = 600
	TLRpcErrorCodes_DBERR_SQL  TLRpcErrorCodes = 600000
	TLRpcErrorCodes_DBERR_CONN TLRpcErrorCodes = 600001
	// db error
	TLRpcErrorCodes_NOTRETURN_CLIENT TLRpcErrorCodes = 700
)

var TLRpcErrorCodes_name = map[int32]string{
	0:      "ERROR_CODE_OK",
	303000: "FILE_MIGRATE_X",
	303001: "PHONE_MIGRATE_X",
	303002: "NETWORK_MIGRATE_X",
	303003: "USER_MIGRATE_X",
	303:    "ERROR_SEE_OTHER",
	400000: "FIRSTNAME_INVALID",
	400001: "LASTNAME_INVALID",
	400002: "PHONE_NUMBER_INVALID",
	400003: "PHONE_CODE_HASH_EMPTY",
	400004: "PHONE_CODE_EMPTY",
	400005: "PHONE_CODE_EXPIRED",
	400006: "API_ID_INVALID",
	400007: "PHONE_NUMBER_OCCUPIED",
	400008: "PHONE_NUMBER_UNOCCUPIED",
	400009: "USERS_TOO_FEW",
	400010: "USERS_TOO_MUCH",
	400011: "TYPE_CONSTRUCTOR_INVALID",
	400012: "FILE_PART_INVALID",
	400013: "FILE_PART_X_MISSING",
	400014: "MD5_CHECKSUM_INVALID",
	400015: "PHOTO_INVALID_DIMENSIONS",
	400016: "FIELD_NAME_INVALID",
	400017: "FIELD_NAME_EMPTY",
	400018: "MSG_WAIT_FAILED",
	400019: "PARTICIPANT_VERSION_OUTDATED",
	400020: "USER_RESTRICTED",
	400021: "NAME_NOT_MODIFIED",
	400022: "USER_NOT_MUTUAL_CONTACT",
	400023: "BOT_GROUPS_BLOCKED",
	400024: "GUEST_USER_NOT_EXISTS",
	400400: "USER_NOT_EXISTS",
	400401: "TEAM_NOT_EXISTS",
	400410: "TEAM_EXPEL_USER_CAN_NOT_EXPEL_YOURSELF_CODE",
	400411: "TEAM_EXPEL_USER_USER_NOT_IN_TEAM_CODE",
	400412: "TEAM_EXPEL_USER_ADMIN_CAN_NOT_EXPEL_ADMIN_AND_OWNER_CODE",
	400413: "TEAM_EXPEL_USER_NOT_ADMIN_CODE",
	400420: "TEAM_INVITE_JOIN_INVITEES_NOT_EXISTS_CODE",
	400421: "TEAM_INVITE_JOIN_ALREADY_IN_TEAM_CODE",
	400430: "TEAM_JOIN_ALREADY_IN_TEAM_CODE",
	400440: "TEAM_QUIT_NOT_IN_TEAM_CODE",
	400450: "TEAM_UPDATE_NOT_PERMISSION_CODE",
	400451: "TEAM_UPDATE_HANDOVER_PERSON_NOT_IN_TEAM_CODE",
	400500: "FILE_REFERENCE_X",
	400501: "FILE_TOKEN_INVALID",
	400502: "REQUEST_TOKEN_INVALID",
	400025: "PHONE_CODE_INVALID",
	400030: "PHONE_NUMBER_BANNED",
	400040: "SESSION_PASSWORD_NEEDED",
	400050: "CODE_INVALID",
	400051: "PASSWORD_HASH_INVALID",
	400052: "NEW_PASSWORD_BAD",
	400053: "NEW_SALT_INVALID",
	400054: "EMAIL_INVALID",
	400055: "EMAIL_UNCONFIRMED",
	400060: "USERNAME_INVALID",
	400061: "USERNAME_OCCUPIED",
	400062: "USERNAMES_UNAVAILABLE",
	400063: "USERNAME_NOT_MODIFIED",
	400064: "USERNAME_NOT_OCCUPIED",
	400070: "CHAT_ID_INVALID",
	400071: "CHAT_NOT_MODIFIED",
	400072: "PARTICIPANT_NOT_EXISTS",
	400073: "NO_EDIT_CHAT_PERMISSION",
	400074: "CHAT_TITLE_NOT_MODIFIED",
	400075: "NO_CHAT_TITLE",
	400076: "CHAT_ABOUT_NOT_MODIFIED",
	400077: "CHAT_ADMIN_REQUIRED",
	400078: "PARTICIPANT_EXISTED",
	400080: "CHANNEL_PRIVATE",
	400081: "CHANNEL_PUBLIC_GROUP_NA",
	400082: "USER_BANNED_IN_CHANNEL",
	40083:  "CHANNELS_ADMIN_PUBLIC_TOO_MUCH",
	400084: "CHANNELS_TOO_MUCH",
	400085: "NO_INVITE_CHANNEL_PERMISSION",
	400090: "INVITE_HASH_EXPIRED",
	400091: "INVITE_HASH_INVALID",
	400200: "ACCESS_HASH_INVALID",
	400201: "INPUT_CHANNEL_EMPTY",
	400202: "USER_NOT_PARTICIPANT",
	400203: "PEER_ID_INVALID",
	400204: "CHANNEL_ID_INVALID",
	400210: "MESSAGE_ID_INVALID",
	400211: "MESSAGE_EDIT_TIME_EXPIRED",
	400212: "MESSAGE_NOT_MODIFIED",
	400213: "MESSAGE_EMPTY",
	400300: "USER_LEFT_CHAT",
	400301: "USER_KICKED",
	400302: "USER_ALREADY_PARTICIPANT",
	400:    "BAD_REQUEST",
	401000: "AUTH_KEY_UNREGISTERED",
	401001: "AUTH_KEY_INVALID",
	401002: "USER_DEACTIVATED",
	401003: "SESSION_REVOKED",
	401004: "SESSION_EXPIRED",
	401005: "ACTIVE_USER_REQUIRED",
	401006: "AUTH_KEY_PERM_EMPTY",
	401:    "UNAUTHORIZED",
	403001: "USER_PRIVACY_RESTRICTED",
	403002: "CALL_PROTOCOL_LAYER_INVALID",
	403:    "FORBIDDEN",
	406000: "ERROR_LOCALIZED",
	406:    "LOCALIZED",
	420000: "FLOOD_WAIT_X",
	420:    "FLOOD",
	500:    "INTERNAL",
	500000: "INTERNAL_SERVER_ERROR",
	501:    "OTHER",
	502:    "OTHER2",
	600:    "DBERR",
	600000: "DBERR_SQL",
	600001: "DBERR_CONN",
	700:    "NOTRETURN_CLIENT",
}
var TLRpcErrorCodes_value = map[string]int32{
	"ERROR_CODE_OK":                               0,
	"FILE_MIGRATE_X":                              303000,
	"PHONE_MIGRATE_X":                             303001,
	"NETWORK_MIGRATE_X":                           303002,
	"USER_MIGRATE_X":                              303003,
	"ERROR_SEE_OTHER":                             303,
	"FIRSTNAME_INVALID":                           400000,
	"LASTNAME_INVALID":                            400001,
	"PHONE_NUMBER_INVALID":                        400002,
	"PHONE_CODE_HASH_EMPTY":                       400003,
	"PHONE_CODE_EMPTY":                            400004,
	"PHONE_CODE_EXPIRED":                          400005,
	"API_ID_INVALID":                              400006,
	"PHONE_NUMBER_OCCUPIED":                       400007,
	"PHONE_NUMBER_UNOCCUPIED":                     400008,
	"USERS_TOO_FEW":                               400009,
	"USERS_TOO_MUCH":                              400010,
	"TYPE_CONSTRUCTOR_INVALID":                    400011,
	"FILE_PART_INVALID":                           400012,
	"FILE_PART_X_MISSING":                         400013,
	"MD5_CHECKSUM_INVALID":                        400014,
	"PHOTO_INVALID_DIMENSIONS":                    400015,
	"FIELD_NAME_INVALID":                          400016,
	"FIELD_NAME_EMPTY":                            400017,
	"MSG_WAIT_FAILED":                             400018,
	"PARTICIPANT_VERSION_OUTDATED":                400019,
	"USER_RESTRICTED":                             400020,
	"NAME_NOT_MODIFIED":                           400021,
	"USER_NOT_MUTUAL_CONTACT":                     400022,
	"BOT_GROUPS_BLOCKED":                          400023,
	"GUEST_USER_NOT_EXISTS":                       400024,
	"USER_NOT_EXISTS":                             400400,
	"TEAM_NOT_EXISTS":                             400401,
	"TEAM_EXPEL_USER_CAN_NOT_EXPEL_YOURSELF_CODE": 400410,
	"TEAM_EXPEL_USER_USER_NOT_IN_TEAM_CODE":       400411,
	"TEAM_EXPEL_USER_ADMIN_CAN_NOT_EXPEL_ADMIN_AND_OWNER_CODE": 400412,
	"TEAM_EXPEL_USER_NOT_ADMIN_CODE":                           400413,
	"TEAM_INVITE_JOIN_INVITEES_NOT_EXISTS_CODE":                400420,
	"TEAM_INVITE_JOIN_ALREADY_IN_TEAM_CODE":                    400421,
	"TEAM_JOIN_ALREADY_IN_TEAM_CODE":                           400430,
	"TEAM_QUIT_NOT_IN_TEAM_CODE":                               400440,
	"TEAM_UPDATE_NOT_PERMISSION_CODE":                          400450,
	"TEAM_UPDATE_HANDOVER_PERSON_NOT_IN_TEAM_CODE":             400451,
	"FILE_REFERENCE_X":                                         400500,
	"FILE_TOKEN_INVALID":                                       400501,
	"REQUEST_TOKEN_INVALID":                                    400502,
	"PHONE_CODE_INVALID":                                       400025,
	"PHONE_NUMBER_BANNED":                                      400030,
	"SESSION_PASSWORD_NEEDED":                                  400040,
	"CODE_INVALID":                                             400050,
	"PASSWORD_HASH_INVALID":                                    400051,
	"NEW_PASSWORD_BAD":                                         400052,
	"NEW_SALT_INVALID":                                         400053,
	"EMAIL_INVALID":                                            400054,
	"EMAIL_UNCONFIRMED":                                        400055,
	"USERNAME_INVALID":                                         400060,
	"USERNAME_OCCUPIED":                                        400061,
	"USERNAMES_UNAVAILABLE":                                    400062,
	"USERNAME_NOT_MODIFIED":                                    400063,
	"USERNAME_NOT_OCCUPIED":                                    400064,
	"CHAT_ID_INVALID":                                          400070,
	"CHAT_NOT_MODIFIED":                                        400071,
	"PARTICIPANT_NOT_EXISTS":                                   400072,
	"NO_EDIT_CHAT_PERMISSION":                                  400073,
	"CHAT_TITLE_NOT_MODIFIED":                                  400074,
	"NO_CHAT_TITLE":                                            400075,
	"CHAT_ABOUT_NOT_MODIFIED":                                  400076,
	"CHAT_ADMIN_REQUIRED":                                      400077,
	"PARTICIPANT_EXISTED":                                      400078,
	"CHANNEL_PRIVATE":                                          400080,
	"CHANNEL_PUBLIC_GROUP_NA":                                  400081,
	"USER_BANNED_IN_CHANNEL":                                   400082,
	"CHANNELS_ADMIN_PUBLIC_TOO_MUCH":                           40083,
	"CHANNELS_TOO_MUCH":                                        400084,
	"NO_INVITE_CHANNEL_PERMISSION":                             400085,
	"INVITE_HASH_EXPIRED":                                      400090,
	"INVITE_HASH_INVALID":                                      400091,
	"ACCESS_HASH_INVALID":                                      400200,
	"INPUT_CHANNEL_EMPTY":                                      400201,
	"USER_NOT_PARTICIPANT":                                     400202,
	"PEER_ID_INVALID":                                          400203,
	"CHANNEL_ID_INVALID":                                       400204,
	"MESSAGE_ID_INVALID":                                       400210,
	"MESSAGE_EDIT_TIME_EXPIRED":                                400211,
	"MESSAGE_NOT_MODIFIED":                                     400212,
	"MESSAGE_EMPTY":                                            400213,
	"USER_LEFT_CHAT":                                           400300,
	"USER_KICKED":                                              400301,
	"USER_ALREADY_PARTICIPANT":                                 400302,
	"BAD_REQUEST":                                              400,
	"AUTH_KEY_UNREGISTERED":                                    401000,
	"AUTH_KEY_INVALID":                                         401001,
	"USER_DEACTIVATED":                                         401002,
	"SESSION_REVOKED":                                          401003,
	"SESSION_EXPIRED":                                          401004,
	"ACTIVE_USER_REQUIRED":                                     401005,
	"AUTH_KEY_PERM_EMPTY":                                      401006,
	"UNAUTHORIZED":                                             401,
	"USER_PRIVACY_RESTRICTED":                                  403001,
	"CALL_PROTOCOL_LAYER_INVALID":                              403002,
	"FORBIDDEN":                                                403,
	"ERROR_LOCALIZED":                                          406000,
	"LOCALIZED":                                                406,
	"FLOOD_WAIT_X":                                             420000,
	"FLOOD":                                                    420,
	"INTERNAL":                                                 500,
	"INTERNAL_SERVER_ERROR":                                    500000,
	"OTHER":                                                    501,
	"OTHER2":                                                   502,
	"DBERR":                                                    600,
	"DBERR_SQL":                                                600000,
	"DBERR_CONN":                                               600001,
	"NOTRETURN_CLIENT":                                         700,
}

func (x TLRpcErrorCodes) String() string {
	return proto.EnumName(TLRpcErrorCodes_name, int32(x))
}
func (TLRpcErrorCodes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_rpc_error_codes_410114e48a170532, []int{0}
}

func init() {
	proto.RegisterEnum("mtproto.TLRpcErrorCodes", TLRpcErrorCodes_name, TLRpcErrorCodes_value)
}

func init() {
	proto.RegisterFile("rpc_error_codes.proto", fileDescriptor_rpc_error_codes_410114e48a170532)
}

var fileDescriptor_rpc_error_codes_410114e48a170532 = []byte{
	// 1521 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x57, 0x4b, 0x8c, 0x14, 0xc7,
	0x19, 0x8e, 0xd8, 0x00, 0xa1, 0x78, 0x6c, 0x51, 0xb0, 0xd0, 0x3c, 0x02, 0x49, 0x04, 0x52, 0x12,
	0xa2, 0x8d, 0x42, 0x14, 0x29, 0xa7, 0x48, 0x35, 0x5d, 0xff, 0xec, 0x54, 0xb6, 0xbb, 0xaa, 0xa9,
	0xaa, 0xde, 0x47, 0x2e, 0xa5, 0xb0, 0x59, 0x45, 0x48, 0x81, 0x45, 0x1b, 0x72, 0xcf, 0xfb, 0xfd,
	0x80, 0x90, 0x10, 0x1e, 0x49, 0xc4, 0x81, 0x48, 0x39, 0x24, 0x44, 0x8a, 0xdd, 0xb3, 0x83, 0x35,
	0xf6, 0x62, 0x2c, 0xd9, 0x3c, 0xd6, 0xc6, 0x60, 0x90, 0x2c, 0xfb, 0xe8, 0x8b, 0xdf, 0xf2, 0x01,
	0xf0, 0xd5, 0xaa, 0xaa, 0x9e, 0x9e, 0x9e, 0xc1, 0xbe, 0xf5, 0x7c, 0xdf, 0xff, 0xae, 0xff, 0xff,
	0xab, 0x06, 0x8d, 0x2d, 0x1e, 0x9f, 0xb3, 0xf3, 0x8b, 0x8b, 0x0b, 0x8b, 0x76, 0x6e, 0xe1, 0x7b,
	0xf3, 0x3f, 0x1c, 0x3f, 0xbe, 0xb8, 0x70, 0x62, 0x81, 0xac, 0x3d, 0x7a, 0xc2, 0x7f, 0x7c, 0xf9,
	0xc3, 0xed, 0x68, 0xd4, 0x24, 0xea, 0xf8, 0x1c, 0x38, 0x99, 0xd8, 0x89, 0x90, 0xcd, 0x68, 0x23,
	0x28, 0x25, 0x95, 0x8d, 0x25, 0x03, 0x2b, 0x27, 0xf1, 0xa7, 0xc8, 0x56, 0xb4, 0xa9, 0xc9, 0x13,
	0xb0, 0x29, 0x9f, 0x50, 0xd4, 0x80, 0x9d, 0xc1, 0x67, 0x97, 0x09, 0x19, 0x43, 0xa3, 0x59, 0x4b,
	0x8a, 0x3a, 0x7c, 0x6e, 0x99, 0x90, 0xed, 0x68, 0xb3, 0x00, 0x33, 0x2d, 0xd5, 0x64, 0x8d, 0x38,
	0xbf, 0x4c, 0x9c, 0x95, 0x5c, 0x83, 0xaa, 0xa1, 0x17, 0x3c, 0x3a, 0x1a, 0xdc, 0x69, 0x00, 0x2b,
	0x4d, 0x0b, 0x14, 0xfe, 0xdf, 0x2a, 0x67, 0xa4, 0xc9, 0x95, 0x36, 0x82, 0xa6, 0x60, 0xb9, 0x98,
	0xa2, 0x09, 0x67, 0xf8, 0xc7, 0x45, 0x44, 0xb6, 0x21, 0x9c, 0xd0, 0x21, 0xfc, 0x27, 0x45, 0x44,
	0x76, 0xa2, 0xad, 0x21, 0x18, 0x91, 0xa7, 0x0d, 0x50, 0x15, 0xf7, 0xd3, 0x22, 0x22, 0xbb, 0xd0,
	0x58, 0xe0, 0x7c, 0x46, 0x2d, 0xaa, 0x5b, 0x16, 0xd2, 0xcc, 0xcc, 0xe2, 0x9f, 0x05, 0x83, 0x35,
	0x32, 0xe0, 0x3f, 0x2f, 0x22, 0x12, 0x21, 0x52, 0xc7, 0x67, 0x32, 0xae, 0x80, 0xe1, 0x5f, 0x14,
	0x91, 0xcb, 0x83, 0x66, 0xdc, 0x72, 0x56, 0x39, 0xf9, 0x65, 0xdd, 0x49, 0x19, 0x80, 0x8c, 0xe3,
	0x3c, 0xe3, 0xc0, 0xf0, 0xaf, 0x8a, 0x88, 0x7c, 0x16, 0x6d, 0x1f, 0x20, 0x73, 0x51, 0xd1, 0xbf,
	0x2e, 0x22, 0xb2, 0x05, 0x6d, 0x74, 0x95, 0xd1, 0xd6, 0x48, 0x69, 0x9b, 0x30, 0x8d, 0x7f, 0x13,
	0xdc, 0xf4, 0xc1, 0x34, 0x8f, 0x5b, 0xf8, 0xb7, 0x45, 0x44, 0xf6, 0xa0, 0xc8, 0xcc, 0x66, 0x2e,
	0x2a, 0xa1, 0x8d, 0xca, 0x63, 0x23, 0xfb, 0xb9, 0xfe, 0xae, 0x88, 0x42, 0xe1, 0x12, 0xb0, 0x19,
	0x55, 0xa6, 0x22, 0x7e, 0x5f, 0x44, 0x64, 0x07, 0xda, 0xd2, 0x27, 0x66, 0x6c, 0xca, 0xb5, 0xe6,
	0x62, 0x02, 0xff, 0x21, 0xd4, 0x2e, 0x65, 0xdf, 0xb0, 0x71, 0x0b, 0xe2, 0x49, 0x9d, 0xa7, 0x95,
	0xda, 0x1f, 0x83, 0xbf, 0xac, 0x25, 0x8d, 0xec, 0x81, 0x96, 0xf1, 0x14, 0x84, 0xe6, 0x52, 0x68,
	0xfc, 0xa7, 0x50, 0xa6, 0x26, 0x87, 0x84, 0xd9, 0x81, 0x13, 0x39, 0x19, 0x0a, 0x5b, 0x63, 0x42,
	0x61, 0x4f, 0x15, 0x91, 0x6b, 0x9b, 0x54, 0x4f, 0xd8, 0x69, 0xca, 0x8d, 0x6d, 0x52, 0x9e, 0x00,
	0xc3, 0x7f, 0x2e, 0x22, 0xf2, 0x05, 0xb4, 0xdb, 0x85, 0xc6, 0x63, 0x9e, 0x51, 0x61, 0xec, 0x14,
	0x28, 0xe7, 0xc4, 0xca, 0xdc, 0x30, 0x6a, 0x80, 0xe1, 0xd3, 0x41, 0xd5, 0x77, 0x90, 0x02, 0x6d,
	0x14, 0x8f, 0x1d, 0xfc, 0x97, 0x90, 0xb3, 0xf7, 0x21, 0xa4, 0xb1, 0xa9, 0x64, 0xbc, 0xe9, 0xea,
	0xfa, 0xd7, 0x50, 0x76, 0x2f, 0xef, 0x89, 0xdc, 0xe4, 0x34, 0x71, 0x75, 0x33, 0x34, 0x36, 0xf8,
	0x4c, 0x88, 0xbd, 0x21, 0x8d, 0x9d, 0x50, 0x32, 0xcf, 0xb4, 0x6d, 0x24, 0x32, 0x9e, 0x04, 0x86,
	0xff, 0x16, 0x0e, 0x73, 0x22, 0x07, 0x6d, 0x6c, 0xa5, 0x0e, 0x33, 0x5c, 0x1b, 0x8d, 0xcf, 0xd6,
	0xa2, 0xa8, 0xc1, 0x27, 0x3b, 0x1e, 0x36, 0x40, 0xd3, 0x3a, 0x7c, 0xaa, 0x13, 0x91, 0xaf, 0xa1,
	0x03, 0x1e, 0x86, 0x99, 0x0c, 0x92, 0x60, 0x2f, 0xa6, 0xa2, 0x94, 0x72, 0xd0, 0xac, 0xcc, 0x95,
	0x86, 0xa4, 0xe9, 0x1b, 0x0d, 0x9f, 0xef, 0x44, 0xe4, 0x00, 0xda, 0x3f, 0xac, 0x52, 0x39, 0xe4,
	0xc2, 0x7a, 0xce, 0x0b, 0x5f, 0xe8, 0x44, 0xe4, 0x5b, 0xe8, 0x9b, 0xc3, 0xc2, 0x94, 0xa5, 0x5c,
	0x0c, 0x79, 0x09, 0x18, 0x15, 0xcc, 0xca, 0x69, 0x01, 0x61, 0xb8, 0xf1, 0xdf, 0x3b, 0x11, 0xd9,
	0x87, 0xf6, 0x0c, 0xeb, 0x3b, 0xad, 0xd2, 0x86, 0x93, 0xfa, 0x47, 0x27, 0x22, 0x5f, 0x45, 0x5f,
	0xf2, 0x52, 0x5c, 0x4c, 0x71, 0x03, 0xf6, 0xdb, 0x92, 0x8b, 0xf2, 0x1b, 0x74, 0x2d, 0xe3, 0xa0,
	0x70, 0xa9, 0x96, 0x43, 0x5d, 0x81, 0x26, 0x0a, 0x28, 0x9b, 0x1d, 0xcc, 0xe1, 0x5f, 0xb5, 0x18,
	0x3e, 0x59, 0xea, 0x72, 0x27, 0x22, 0x9f, 0x43, 0x3b, 0x3d, 0x70, 0x28, 0xe7, 0xe6, 0xf1, 0x5a,
	0x74, 0x3a, 0x11, 0xd9, 0x8f, 0xf6, 0x7a, 0x20, 0xcf, 0x5c, 0xcf, 0x78, 0x99, 0x0c, 0x94, 0x6f,
	0x75, 0x59, 0x26, 0x73, 0xad, 0x13, 0x91, 0x83, 0xe8, 0x2b, 0x75, 0xb1, 0x16, 0x15, 0x4c, 0x4e,
	0x81, 0x72, 0xb2, 0x5a, 0x8a, 0xc7, 0x4d, 0x3f, 0xd7, 0x29, 0xbb, 0x39, 0x01, 0xab, 0xa0, 0x09,
	0x0a, 0x44, 0xec, 0xd6, 0xd7, 0x83, 0x4e, 0xd9, 0xff, 0x09, 0x58, 0x23, 0x27, 0x41, 0x54, 0xfd,
	0xff, 0xb0, 0xe3, 0x7b, 0x48, 0xc1, 0x21, 0xdf, 0x45, 0x83, 0xe4, 0xa3, 0xce, 0xf0, 0x76, 0xe9,
	0x31, 0xe7, 0xc2, 0x9c, 0x0e, 0xac, 0x8a, 0x06, 0x15, 0x02, 0x18, 0xfe, 0x67, 0x68, 0x67, 0x0d,
	0x21, 0x97, 0x8c, 0x6a, 0x3d, 0x2d, 0x15, 0xb3, 0x02, 0x80, 0x01, 0xc3, 0xff, 0x2e, 0x22, 0x42,
	0xd0, 0x86, 0x01, 0x6b, 0xff, 0x2f, 0xb7, 0x52, 0x4f, 0xd4, 0x2f, 0xbe, 0x1e, 0xf9, 0x44, 0x98,
	0x50, 0x01, 0xd3, 0x7d, 0x5b, 0x0d, 0xca, 0xf0, 0x93, 0x7d, 0x5c, 0xd3, 0xa4, 0xbf, 0x42, 0x8a,
	0xb0, 0xa6, 0x20, 0xa5, 0x3c, 0xa9, 0xc0, 0x76, 0x18, 0xbe, 0x00, 0xe6, 0x22, 0x96, 0xa2, 0xc9,
	0x55, 0x0a, 0x0c, 0x2f, 0x05, 0x2b, 0xae, 0x9b, 0x06, 0xf6, 0x42, 0x37, 0x28, 0x54, 0x78, 0xb5,
	0x05, 0x9f, 0x0e, 0xb1, 0xf6, 0x08, 0x6d, 0x73, 0x41, 0xa7, 0x28, 0x4f, 0x68, 0x23, 0x01, 0xfc,
	0xcc, 0x20, 0x39, 0x38, 0xe7, 0xcb, 0x1f, 0x43, 0x56, 0x66, 0xaf, 0x86, 0x71, 0x8d, 0x5b, 0xd4,
	0xd4, 0xf7, 0xf5, 0xf3, 0x21, 0x0c, 0x0f, 0x0f, 0x18, 0x7b, 0xa1, 0x88, 0xc8, 0x6e, 0xb4, 0xad,
	0xbe, 0x88, 0x6a, 0xe3, 0x7c, 0x3d, 0x9c, 0x81, 0x90, 0x16, 0x18, 0x37, 0xd6, 0xab, 0xf7, 0xfb,
	0x0b, 0xdf, 0x08, 0xb4, 0x87, 0x0d, 0x37, 0xc9, 0x50, 0xa0, 0x37, 0x43, 0x05, 0x85, 0xb4, 0x7d,
	0x09, 0x7c, 0xab, 0xa6, 0x43, 0x1b, 0x32, 0x1f, 0x8a, 0x67, 0x25, 0x34, 0x44, 0xa0, 0xfd, 0x44,
	0xba, 0x96, 0xf2, 0x37, 0xd1, 0x8b, 0x65, 0xaf, 0xd4, 0x42, 0xf5, 0x61, 0x02, 0xc3, 0x2f, 0x55,
	0x59, 0x0b, 0x01, 0x89, 0xcd, 0x14, 0x9f, 0xa2, 0x06, 0xf0, 0xcb, 0x95, 0xaf, 0x00, 0xe7, 0x8d,
	0x84, 0xc7, 0x61, 0xfb, 0x59, 0x41, 0xf1, 0x9d, 0x90, 0xbb, 0xdf, 0x00, 0xa1, 0xe9, 0xdc, 0x14,
	0x94, 0xd2, 0xf8, 0x6e, 0xe1, 0xc7, 0xb4, 0xfc, 0xa9, 0xcb, 0x68, 0x4a, 0x1b, 0xd5, 0x0d, 0x75,
	0xfa, 0xca, 0xaa, 0xb2, 0xb0, 0x41, 0xaa, 0x22, 0xee, 0x85, 0x0d, 0x2f, 0x64, 0x6f, 0x21, 0x54,
	0x51, 0xf4, 0xeb, 0x77, 0x3f, 0x64, 0x54, 0x0a, 0x84, 0x6b, 0xba, 0xbc, 0x76, 0x5f, 0x7b, 0x9c,
	0xea, 0x9d, 0xe5, 0xeb, 0x81, 0xa2, 0x71, 0x0c, 0x5a, 0x0f, 0x52, 0xd7, 0xdb, 0xa5, 0x56, 0x96,
	0x9b, 0xca, 0x61, 0xb8, 0x88, 0x6e, 0xb4, 0xfd, 0xb5, 0x57, 0xad, 0xbb, 0x5a, 0x19, 0xf1, 0xcd,
	0xb6, 0x2f, 0x5f, 0x06, 0xee, 0x19, 0xd1, 0x6f, 0x9a, 0x5b, 0x6d, 0x3f, 0xb6, 0x3d, 0x3b, 0x35,
	0x66, 0x25, 0x30, 0x29, 0x68, 0x4d, 0x27, 0xa0, 0xce, 0xdc, 0x6d, 0x47, 0x64, 0x2f, 0xda, 0xd1,
	0x63, 0x7c, 0xdb, 0x18, 0x9e, 0xf6, 0xdf, 0x13, 0xaf, 0x84, 0x38, 0x7a, 0x02, 0x03, 0x87, 0x7f,
	0xaf, 0xed, 0x1b, 0xa6, 0x52, 0xf6, 0x81, 0xdf, 0x6f, 0x57, 0x2f, 0x03, 0x9b, 0x40, 0x33, 0x74,
	0x21, 0xfe, 0xcf, 0x52, 0x44, 0x36, 0xa3, 0xf5, 0x1e, 0x9d, 0xe4, 0xfe, 0x1a, 0xfb, 0xef, 0x92,
	0xbf, 0xbc, 0xc3, 0x85, 0x50, 0xae, 0xd4, 0x7a, 0x96, 0x97, 0x97, 0x22, 0x82, 0xd1, 0xfa, 0x06,
	0x65, 0xb6, 0x5c, 0x53, 0xf8, 0xe4, 0x88, 0x9b, 0x24, 0x9a, 0x9b, 0x96, 0x9d, 0x84, 0x59, 0x9b,
	0x0b, 0x05, 0x13, 0xae, 0xa3, 0x5c, 0xa0, 0x6f, 0x76, 0xfd, 0x44, 0x57, 0x64, 0x2f, 0xc3, 0xb7,
	0xba, 0xd5, 0xa4, 0x5b, 0x06, 0x34, 0x36, 0xbe, 0xd7, 0x18, 0x7e, 0xbb, 0xeb, 0x8b, 0xd8, 0xdb,
	0x57, 0x0a, 0xa6, 0xa4, 0x8b, 0xea, 0x9d, 0x41, 0xb8, 0x57, 0x86, 0x77, 0xbb, 0xbe, 0x0c, 0x5e,
	0x1d, 0x6c, 0x79, 0xc7, 0x97, 0x8d, 0xfe, 0x5e, 0x37, 0x1c, 0x70, 0xcf, 0xb3, 0xeb, 0x98, 0xb2,
	0x18, 0xef, 0x77, 0x5d, 0xda, 0x1b, 0x72, 0xe1, 0x48, 0xa9, 0xf8, 0x77, 0x80, 0xe1, 0x53, 0x23,
	0xd5, 0xb5, 0xef, 0x1b, 0x3f, 0x9e, 0xad, 0x3f, 0x17, 0xae, 0xac, 0x44, 0xe4, 0xf3, 0x68, 0x57,
	0x4c, 0x13, 0x37, 0x17, 0xd2, 0xc8, 0x58, 0x26, 0x36, 0xa1, 0xb3, 0xb5, 0x17, 0xe3, 0x53, 0x2b,
	0x11, 0xd9, 0x84, 0xd6, 0x35, 0xa5, 0x6a, 0x70, 0xc6, 0x40, 0xe0, 0xd3, 0x23, 0x2e, 0xe4, 0xf0,
	0x48, 0x4d, 0x64, 0x4c, 0x13, 0xef, 0xe7, 0x83, 0x37, 0xbc, 0x58, 0x1f, 0x38, 0x33, 0xe2, 0x36,
	0x70, 0x33, 0x91, 0x92, 0x85, 0xc7, 0xcd, 0x0c, 0xbe, 0x78, 0x67, 0x07, 0x41, 0x68, 0xb5, 0xc7,
	0xf0, 0xa5, 0x11, 0xb2, 0x11, 0x7d, 0x86, 0x0b, 0xe3, 0x16, 0x55, 0x82, 0x1f, 0xf8, 0x62, 0xf7,
	0x7e, 0x5a, 0x0d, 0xca, 0x5d, 0x41, 0xde, 0x0b, 0xbe, 0x78, 0x6d, 0x8f, 0xd3, 0x0b, 0xaf, 0xe1,
	0x87, 0x23, 0x64, 0x3d, 0x5a, 0xe3, 0xbf, 0x0f, 0xe2, 0x47, 0x23, 0x8e, 0x60, 0x0d, 0x50, 0x0a,
	0xbf, 0xfa, 0x69, 0x32, 0x8a, 0xd6, 0xf9, 0x6f, 0xab, 0x0f, 0x25, 0xf8, 0xea, 0xed, 0x7d, 0x04,
	0x23, 0x14, 0x80, 0x58, 0x0a, 0x81, 0x9f, 0xbd, 0xbd, 0x8f, 0x8c, 0x21, 0x2c, 0xa4, 0x51, 0x60,
	0x72, 0x25, 0x6c, 0x9c, 0x70, 0x10, 0x06, 0x77, 0x57, 0x37, 0xbe, 0x88, 0x76, 0xcd, 0x2d, 0x1c,
	0x1d, 0x3f, 0x36, 0x7f, 0xf8, 0x47, 0x3f, 0xf8, 0xee, 0x91, 0xa3, 0xe3, 0xf3, 0xc7, 0xbe, 0x7f,
	0xe4, 0xd8, 0xfc, 0x78, 0xf9, 0xc7, 0xa0, 0xb1, 0x36, 0x35, 0x99, 0xfb, 0x68, 0xad, 0x3a, 0xbc,
	0xc6, 0x23, 0x5f, 0xff, 0x28, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xaa, 0xdc, 0xbb, 0x4c, 0x0c, 0x00,
	0x00,
}
